dist: trusty
language: node_js
node_js:
  - 6

env:
  global:
    - CC=clang-3.8
    - CXX=clang++-3.8

addons:
  postgresql: '9.6'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - libstdc++-5-dev

before_install:
  - sudo add-apt-repository ppa:mapnik/nightly-trunk -y
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - sudo apt-get install libmapnik libmapnik-dev mapnik-utils mapnik-vector-tile -y
  - sudo apt-get install mapnik-input-plugin-gdal mapnik-input-plugin-ogr mapnik-input-plugin-postgis -y

notifications:
  email: false

deploy:
  provider: npm
  email: hello@langa.io
  api_key:
    secure: R++4cQf70EkFvh6oJOaosDC8RUWg8HyK8LYZmdvRC35o0A7Q64esugDVAgKOJ9gvQCVJhUX9dxHZ681Xw6/P2+sMSeHP47lsAK5VxExlWpJwxmIPQaUuVT4sqXy8P/cXe5qvTba9+vYCLSees5fi/RMlJkvATwX/7zzhxNxlpq6qN34LMd+HuI3/6uay/qrG944M7KzxgXUWxVbMPOG78J7bHuAWjwZ7j37E+UAH3t5bR1k6WRkvI8KXZGrlbMgldILQcRt6Jh5SPkE8rV9kSmPEJR9CM+8GvEssZUYBdY6jlz+BbtFvF2ymiMVChpE6KbC2UTnhGIXZLxsbBKYKj3L8svXvelTRGXhKVRITUI4YOz2qVWJFjBxRDb22/XqYVclSrdASgMQVeOgnwoHP2wXIFTGdrJ02hUuTS/o8MU5JJVb4Q5JoiNF0rFRnUqD7tC73UdllS50/QBQmxAA/c4+Af+bh7vrHELLpoZy9xnS+3InhE1baO7F3GlRRJ6vc/1RqfB+OZDYw6LcmthwJVPaFVOtqNxZO+hVFB3ye3te7oI+TW4O5S6SMpsxPaYhlF8JdnK3gCDv7gx9sNrfgV2or5n1WNmW9x0YEIUzECWgiAs50aG0YZoauNPs25bEJ3xIxA3sjPek2eT9rwRYHUyTNptTs1fzUwdQGBF1HfnI=
  on:
    tags: true
    repo: langateam/trailpack-mapnik
    node: 6
